### ISSUE TITLE
Code blocks

### ISSUE THREAD

**Issue by renatorib** [renatorib/hubbo-template-posts#6]
---
slug: code-blocks
---

## Syntax highlight

JS/TS

```tsx
const { posts } = await hubbo.findPosts({
  label: "type:post"
});
```

JSON

```json
{
  "name": "hubbo",
  "version": "1.0.0",
  "type": "module"
}
```

CSS

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer utilities {
  .text-balance {
    text-wrap: balance;
  }
}
```

HTML

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  Hubbo
</body>
</html>
```

etc...

## Line highlight

```tsx
const { posts } = await hubbo.findPosts({
  label: "type:post" // [!code highlight]
});
```

## Word highlight

```tsx /type:post/
const { posts } = await hubbo.findPosts({
  label: "type:post"
});
```

## Diffs highlight

```tsx
const { posts } = await hubbo.findPosts({
  label: "type:post" // [!code --]
  label: "type:article" // [!code ++]
});
```
